title: Заголовок
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Описание сайта
baseurl: "/geneo"
url: "https://panaramix.github.io/"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
